# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/welcome.ipynb
"""

import numpy as np
import matplotlib.pyplot as plt

# Load the dataset
data = np.array([
    [20, 88.6], [16, 71.6], [19.8, 93.3], [18.4, 84.3], [17.1, 80.6],
    [15.5, 75.2], [14.7, 69.7], [17.1, 82.0], [15.4, 69.4], [16.2, 83.3],
    [15.0, 79.6], [17.2, 82.6], [16.0, 80.6], [17.0, 83.5], [14.4, 76.3]
])

x = data[:, 0]
y = data[:, 1]
m = len(x)

# Visualize the data
plt.scatter(x, y, c='b')
plt.title('Cricket Chirps vs Temperature')
plt.xlabel('Chirps/sec')
plt.ylabel('Temperature (°F)')
plt.grid(True)
plt.show()

# Hypothesis function
h = lambda theta0, theta1, x: theta0 + theta1 * x

# Cost function
cost = lambda theta0, theta1, x_i, y_i: 0.5 * (h(theta0, theta1, x_i) - y_i)**2

# Initialization
theta = np.array([0.0, 0.0])      # theta0 and theta1
velocity = np.array([0.0, 0.0])   # momentum vector
alpha = 0.01                      # learning rate
gamma = 0.9                       # momentum factor
epochs = 100                      # number of passes through the data

cost_history = []

for epoch in range(epochs):
    for i in range(m):
        xi, yi = x[i], y[i]
        error = h(theta[0], theta[1], xi) - yi
        grad = np.array([error, error * xi])

        velocity = gamma * velocity + alpha * grad
        theta -= velocity

        cost_history.append(cost(theta[0], theta[1], xi, yi))

print("Final parameters:")
print("theta_0 =", theta[0])
print("theta_1 =", theta[1])


#Cost Convergence Visualization
plt.plot(cost_history)
plt.title("Cost Over Iterations (Momentum)")
plt.xlabel("Iteration")
plt.ylabel("Cost")
plt.grid(True)
plt.show()

#Final Linear Fit

xx = np.linspace(min(x), max(x), 100)
yy = h(theta[0], theta[1], xx)

plt.scatter(x, y, color='blue', label='Data')
plt.plot(xx, yy, color='red', label='Fitted Line')
plt.xlabel('Chirps/sec')
plt.ylabel('Temperature (°F)')
plt.title('Linear Regression with Momentum')
plt.legend()
plt.grid(True)
plt.show()

#validation
from scipy import stats
result = stats.linregress(x, y)
print("Actual intercept:", result.intercept)
print("Actual slope:", result.slope)